In [26]:
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images.shape

(60000, 28, 28)

In [27]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [28]:
test_images.shape

(10000, 28, 28)

In [29]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

##### 神经网络架构

In [30]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='rmsprop',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


##### 准备数据

In [31]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

##### 训练模型

In [32]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.8729 - loss: 0.4409
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9662 - loss: 0.1153
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 9s 20ms/step - accuracy: 0.9775 - loss: 0.0746
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9861 - loss: 0.0493
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9891 - loss: 0.0364


##### 预测

In [34]:
test_digits = test_images[0:10]
y_pred = model.predict(test_digits)
y_pred[0]


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([1.6125064e-08, 2.0721338e-09, 7.0328929e-07, 1.9099954e-05,
       4.2864067e-12, 1.1701031e-08, 5.8931712e-13, 9.9998003e-01,
       1.1123922e-08, 1.4750533e-07], dtype=float32)

In [35]:
y_pred[0].argmax()

np.int64(7)

In [36]:
y_pred[0][7]

np.float32(0.99998003)

In [37]:
test_labels[0]

np.uint8(7)

##### 使用测试数据评估模型

In [40]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9716 - loss: 0.0900
test_acc: 0.975600004196167
